version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:aait-lha
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:aait-lha
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - app-network
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx:aait-lha
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/wordpress
    networks:
      - app-network
    depends_on:
      - wordpress
  redis:
    build: ./requirements/bonus/redis
    image: redis:aait-lha
    container_name: redis
    restart: always
    networks:
      - app-network
    depends_on:
      - wordpress
  static-website:
    build: ./requirements/bonus/static-website
    image: static-website:aait-lha
    container_name: static-website
    networks:
      - app-network
    ports:
      - "8081:80"
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:aait-lha
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - app-network
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:aait-lha
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/ftp/pub
    networks:
      - app-network
  portainer:
    build: ./requirements/bonus/portainer
    image: portainer:aait-lha
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data portainer/portainer-ee
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "9443:9443"
    networks:
      - app-network

volumes:
  mariadb_data:
  wordpress_data:
  portainer_data:

networks:
  app-network: