services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:aait-lha
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inc

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:aait-lha
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inc

  nginx:
    build: ./requirements/nginx
    image: nginx:aait-lha
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/wordpress
    networks:
      - inc

  redis:
    build: ./requirements/bonus/redis
    image: redis:aait-lha
    container_name: redis
    restart: always
    depends_on:
      - wordpress
    networks:
      - inc

  static-website:
    build: ./requirements/bonus/static-website
    image: static-website:aait-lha
    container_name: static-website
    restart: always
    ports:
      - "3000:3000"
    networks:
      - inc

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:aait-lha
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inc

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:aait-lha
    container_name: ftp
    restart: always
    secrets:
      - ftp_password
    env_file:
      - .env
    ports:
      - "21:21"
      - "2000-2100:2000-2100"
    volumes:
      - ftp_data:/var/www/wordpress
    networks:
      - inc

  uptime-kuma:
    build: ./requirements/bonus/uptime-kuma
    image: uptime-kuma:aait-lha
    container_name: uptime-kuma
    volumes:
      - uptime_kuma_data:/home/uptimekuma/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inc
    ports:
      - "3001:3001"
    restart: unless-stopped  

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o : bind
      type : none
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o : bind
      type : none
  ftp_data:
    name: ftp
    driver: local
    driver_opts:
      device: /home/${USER}/data/ftp
      o : bind
      type : none
  uptime_kuma_data:
    name: uptime-kuma
    driver: local
    driver_opts:
      device: /home/${USER}/data/uptime-kuma
      o : bind
      type : none

networks:
  inc:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
